# Generated by Django 4.1.7 on 2023-03-17 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todowork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('isDone', models.BooleanField(default=False)),
                ('desc', models.CharField(max_length=220)),
                ('title', models.CharField(max_length=60)),
            ],
        ),
    ]
